version: '3.9'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/expenditure
      REDIS_URL: redis://redis:6379
      KAFKA_BROKER: kafka:9092
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run dev"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expenditure
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

volumes:
  pgdata:
