services:
  postgres:
    image: postgres:15-alpine
    container_name: expenditure-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expenditure
    ports:
      - "5432:5432"
